# Generated by Django 3.0.4 on 2020-04-21 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevSanction',
            fields=[
                ('ps_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('ps_req', models.IntegerField(default=0)),
                ('ps_san', models.IntegerField(default=0)),
                ('ps_comment', models.TextField(blank=True, max_length=200, verbose_name='Comments')),
                ('ps_dscd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Desg')),
                ('ps_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Unit')),
            ],
        ),
    ]
