# sample data courtesy of generatedata.com

data = [
    {"d_cadre": "CD", "u_name": "CRC", "d_cadre": "CD", "u_id": "2020_U01CRC", "d5": "CLGEN",
     "d_gdesig": "OS/CLERK GENERAL", "d_id": "2020_T1CLGEN", "d_rank": "", "d_discp": "CLERICAL",
     "d_name": "OFFICE SUPDT.", "d_grade": "T/S-A1", "d_gcode": "1", "tot": 0, "san": 0, "req": 6, "comment": ""},
    {"d_cadre": "CD", "u_id": "2020_U01CRC", "d5": "CLGEN", "d_gdesig": "OS/CLERK GENERAL", "d_id": "2020_GSCLGEN",
     "d_rank": "", "d_discp": "CLERICAL", "d_name": "CLERK SPL/SR.CLERK", "d_grade": "GR. SPL", "d_gcode": "10",
     "tot": 2, "san": None, "req": None, "comment": None},
    {"d_cadre": "CD", "u_id": "2020_U01CRC", "d5": "CLGEN", "d_gdesig": "OS/CLERK GENERAL", "d_id": "2020_G1CLGEN",
     "d_rank": "", "d_discp": "CLERICAL", "d_name": "CLERK GEN.", "d_grade": "GR.I", "d_gcode": "11", "tot": 5,
     "san": None, "req": None, "comment": None},
    {"d_cadre": "CD", "u_id": "2020_U01CRC", "d5": "CLGEN", "d_gdesig": "OS/CLERK GENERAL", "d_id": "2020_G2CLGEN",
     "d_rank": "", "d_discp": "CLERICAL", "d_name": "CLERK GEN.", "d_grade": "GR.II", "d_gcode": "12", "tot": 0,
     "san": None, "req": None, "comment": None},
    {"d_cadre": "CD", "u_id": "2020_U01CRC", "d5": "CLGEN", "d_gdesig": "OS/CLERK GENERAL", "d_id": "2020_G3CLGEN",
     "d_rank": "", "d_discp": "CLERICAL", "d_name": "CLERK GEN.", "d_grade": "GR.III", "d_gcode": "13", "tot": 2,
     "san": None, "req": None, "comment": None},
    {"d_cadre": "CD", "u_id": "2020_U01CRC", "d5": "CLGEN", "d_gdesig": "OS/CLERK GENERAL", "d_id": "2020_TACLGEN",
     "d_rank": "", "d_discp": "CLERICAL", "d_name": "OFFICE SUPDT.", "d_grade": "T/S-A", "d_gcode": "2", "tot": 0,
     "san": None, "req": None, "comment": None},
    {"d_cadre": "CD", "u_id": "2020_U01CRC", "d5": "MNOVM", "d_gdesig": "OVERMAN", "d_id": "2020_T1MNOVM", "d_rank": "",
     "d_discp": "MINING", "d_name": "OVERMAN SR.", "d_grade": "T/S-A1", "d_gcode": "1", "tot": 2, "san": None,
     "req": None, "comment": None},
    {"d_cadre": "CD", "u_id": "2020_U01CRC", "d5": "MNOVM", "d_gdesig": "OVERMAN", "d_id": "2020_TAMNOVM", "d_rank": "",
     "d_discp": "MINING", "d_name": "OVERMAN SR.", "d_grade": "T/S-A", "d_gcode": "2", "tot": 0, "san": None,
     "req": None, "comment": None},
    {"d_cadre": "CD", "u_id": "2020_U01CRC", "d5": "MNOVM", "d_gdesig": "OVERMAN", "d_id": "2020_TBMNOVM", "d_rank": "",
     "d_discp": "MINING", "d_name": "OVERMAN", "d_grade": "T/S-B", "d_gcode": "3", "tot": 0, "san": None, "req": None,
     "comment": None},
    {"d_cadre": "CD", "u_id": "2020_U01CRC", "d5": "MNOVM", "d_gdesig": "OVERMAN", "d_id": "2020_TCMNOVM", "d_rank": "",
     "d_discp": "MINING", "d_name": "OVERMAN JR.", "d_grade": "T/S-C", "d_gcode": "4", "tot": 0, "san": None,
     "req": None, "comment": None}]
