"""
Django settings for budget_app project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from logging import INFO

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*)wbj9ml@_s3o-l0d%qugo0(tz%b_0bjb=w*v*b1hhc9^oj-q4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['0.0.0.0', '127.0.0.1']
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'assessment.apps.AssessmentConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tables2',
    'django_filters',
    # 'rangefilter',
    # 'foundation',
    'crispy_forms',
    'bootstrap3',
    'dal',
    'dal_select2',
    'jquery',
    'jquery_ui',
    # 'papertrail',
    # 'auditlog',
    'automated_logging'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'automated_logging.middleware.AutomatedLoggingMiddleware'
]

ROOT_URLCONF = 'budget_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'budget_app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


BUDGET_20_21 = 'database/db_final_approved_2020-21.sqlite3'
BUDGET_HCM = 'database/db_hcm_2020.sqlite3'
BUDGET_EDITED = 'database/db_edited_approved_2020-21.sqlite3'
BUDGET_21_22 = 'database/db_unapproved_2021-22.sqlite3'

CURRENT_DATABASE = BUDGET_21_22
EDIT_ENABLED = True


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, CURRENT_DATABASE),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# STATIC_ROOT = '/home/violetboy/PycharmProjects/budgetApp/static/'
STATIC_URL = '/static/'
# STATICFILES_DIRS = (
#     os.path.join(os.path.dirname(__file__),'static_files_dir',), # or whatever you named it
# )
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static')

# Default settings
BOOTSTRAP3 = {
    # The URL to the jQuery JavaScript file
    'jquery_url': 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js',
}

# from crispy_forms_foundation.settings import *
CRISPY_TEMPLATE_PACK = 'bootstrap'
# CRISPY_ALLOWED_TEMPLATE_PACKS = ('bootstrap', 'uni_form', 'bootstrap3', 'bootstrap4', 'semantic-ui')
# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LOGIN_REDIRECT_URL = 'empl_list'
LOGOUT_REDIRECT_URL = 'login'
# LOGIN_URL = 'login'

AUTOMATED_LOGGING = {
    'exclude': {'model': ['admin', 'session', 'automated_logging', 'basehttp', 'contenttypes', 'migrations'],
                'request': ['GET', 200],
                'unspecified': []},
    'modules': ['request', 'model', 'unspecified'],
    'to_database': True,
    'loglevel': {'model': INFO,
                 'request': INFO},
    'save_na': True,
    'request': {
        'query': False
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'db': {
            'level': 'INFO',
            'class': 'automated_logging.handlers.DatabaseHandler',
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        # 'automated_logging': {
        #     'level': 'INFO',
        #     'handlers': ['db'],
        #     'propagate': True,
        # },
        # 'django': {
        #     'level': 'INFO',
        #     'handlers': ['db'],
        #     'propagate': True,
        # },
    },
}

